services:
  postgres:
    image: postgres:16-alpine
    container_name: telco_pg
    environment:
      POSTGRES_USER: telco
      POSTGRES_PASSWORD: telco
      POSTGRES_DB: telco_dw
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d:ro
      - ./data:/data:ro
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U telco -d telco_dw"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  pgdata: